dashboard/urls.py
from django.contrib import admin
from django.urls import path , include

from . import views




app_name='dashboard'

urlpatterns = [

   
    path('', views.home, name='home'),
    path('login',views.userlogin, name='login' ),
    path('sendpck',views.sendpck, name='sendpck' ),
    path('movepck',views.movepck, name='movepck' ),
    path('arrivepck',views.arrivepck, name='arrivepck' ),
    path('manifest',views.manifest, name='manifest' ),
    path('barcode/', views.generate_barcode, name='barcode'),
    path('page_account_settings/', views.page_account_settings, name='page_account_settings'),
    
  

]

main/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views


app_name = 'main'

urlpatterns = [
     path('', views.home, name='home'),
     path('tracking', views.tracking, name='tracking'),
     path('branches', views.branches, name='branches'),
     path('faq', views.faq, name='faq'),
     path('express', views.express, name='express'),
     path('forwarding', views.forwarding, name='forwarding'),
     path('scan/', views.barcode_scanner, name='barcode_scanner'),
     path('scan2/', views.barcode_scannergemini, name='barcode_scannergemini'),
    
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static



urlpatterns  = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
   
]


    
    
   
   
   
   

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Country(models.Model):
    countryName = models.CharField(max_length=50, unique=True)
    code = models.CharField(max_length=20, null=True)
    def __str__(self):
        return self.countryName


class City(models.Model):
    country = models.ForeignKey(
        Country, null=True, blank=True, on_delete=models.SET_NULL)
    cityName = models.CharField(max_length=50,)
    def __str__(self):
        return self.cityName
    
class AcountUser(models.Model):
    user = models.OneToOneField(
        User, related_name='acountUser_user', on_delete=models.CASCADE)
    acountUserName = models.CharField(max_length=50,)
    acountUserNumber=models.IntegerField(null=True, default=0)
    address = models.TextField(null=True)
    city = models.ForeignKey(City, null=True, on_delete=models.SET_NULL)
    mobileNumber = models.CharField(max_length=30,)
    email = models.CharField(max_length=50,)
    date_created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.acountUserName

    
class CustomerInfo(models.Model):
    customerName = models.CharField(max_length=50,)
    customerNumber=models.IntegerField(null=True, default=0)
    address = models.TextField(null=True)
    country = models.ForeignKey(Country, null=True, on_delete=models.SET_NULL)
    city = models.ForeignKey(City, null=True, on_delete=models.SET_NULL)
    mobileNumber = models.CharField(max_length=30,)
    email = models.CharField(max_length=50,)
    date_created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.customerName
class  Shipment(models.Model):
    type_shipment = (
        ('envelope', 'envelope'),
        ('box', 'box'),    
    )
    status_shipment = (
        ('recipient', 'recipient'),
        ('notrecipient', 'notrecipient'),    
    )
    shipment_number = models.IntegerField(default=0)
    sender_date =models.DateTimeField(auto_now_add=True)
    customer_sender = models.ForeignKey(CustomerInfo, related_name='sender', null=True, on_delete=models.SET_NULL)
    customer_receiver = models.ForeignKey(CustomerInfo, related_name='receiver', null=True, on_delete=models.SET_NULL)
    shipment_destination = models.ForeignKey(City, null=True, on_delete=models.SET_NULL)
    shipment_type = models.CharField(default='envelope',max_length=10,choices=type_shipment)
    number_parts = models.IntegerField(default=1)
    weight  = models.IntegerField(default=1)
    shipment_terms =models.TextField(null=True)
    content = models.TextField(null=True)
    expected_time =models.DateTimeField(auto_now_add=True)
    delivery_date =models.DateTimeField(auto_now_add=True)
    date_created = models.DateTimeField(auto_now_add=True)
    acountUser_giver = models.ForeignKey(AcountUser, related_name='giver', null=True, on_delete=models.SET_NULL)
    acountUser_recipient = models.ForeignKey(AcountUser, related_name='recipient', null=True, on_delete=models.SET_NULL)
    barcode = models.IntegerField(default=1)
    status = models.CharField(default='notrecipient',max_length=30,choices=status_shipment)

    def __str__(self):
        return self.shipment_number
        

    class Movement(models.Model):
        movement_number  = models.IntegerField(default=1)
        movement_date  = models.DateTimeField(auto_now_add=True)
        movement_destination = models.ForeignKey(City, null=True, on_delete=models.SET_NULL)
        acountUser_movement = models.ForeignKey(AcountUser, null=True, on_delete=models.SET_NULL)
        def __str__(self):
            return self.movement_number

dashboard/views.py
from django.shortcuts import render
from django.http import HttpResponse
from PIL import Image, ImageDraw
import barcode
from barcode.writer import ImageWriter
import io


# Create your views here.
def home(request):
        
    return render(request, 'dashboard/home.html', {})

def userlogin(request):
     return render(request, 'dashboard/auth_login.html', {})

def sendpck(request):
     return render(request, 'dashboard/sendpck.html', {})

def movepck(request):
     return render(request, 'dashboard/movepck.html', {})

def arrivepck(request):
     return render(request, 'dashboard/arrivepck.html', {})

def manifest(request):
     return render(request, 'dashboard/manifest.html', {})



def generate_barcode(request):
    try:
        # Create a blank white image
        img = Image.new('RGB', (300, 300), color='white')
        draw = ImageDraw.Draw(img)
        
        # Get the barcode data
        barcode_data = "123456789"  # Example data
        
        # Generate the barcode
        code128 = barcode.get_barcode_class('code128')
        barcode_instance = code128(barcode_data, writer=ImageWriter())
        barcode_image = barcode_instance.render()

        # Paste the barcode onto the image
        img.paste(barcode_image, (10, 10))
        
        # Convert image to bytes
        buffer = io.BytesIO()
        img.save(buffer, format='PNG')
        
        # Return the image as HTTP response
        return HttpResponse(buffer.getvalue(), content_type='image/png')
    except Exception as e:
        # Print the error for debugging purposes
        print("Error generating barcode:", e)
        # Return a generic error response
        return HttpResponse("Error generating barcode", status=500)


def page_account_settings(request):
     return render(request, 'dashboard/page_account_settings.html', {})

main/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    fff=55
    
    return render(request, 'main/home.html', {'fff':fff})



def barcode_scanner(request):
    return render(request, 'main/barcode_scanner.html')

def barcode_scannergemini(request):
    return render(request, 'main/barcode_scannergemini.html')


def tracking(request):
        
    return render(request, 'main/tracking.html', {})

def branches(request):
        
    return render(request, 'main/branches.html', {})

def faq(request):
        
    return render(request, 'main/FAQ.html', {})

def express(request):
        
    return render(request, 'main/express.html', {})

def forwarding(request):
        
    return render(request, 'main/forwarding.html', {})

dashboard/templates/dashboard/barcode.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Barcode Sticker</title>
<style>
    /* CSS for printing */
    @media print {
        /* Set the position of the container to top-left */
        .barcode-container {
            position: absolute;
            left: 0;
            top: 0;
        }
    }
</style>
</head>
<body>
    <!-- Container for the barcode -->
    <div class="barcode-container">
        <!-- Display the barcode image -->
        <img src="{% url 'generate_barcode' %}" alt="Barcode Image">
    </div>
</body>
</html>

dashboard/templates/dashboard/navbar.html
{% load static  %}


<nav class="header-navbar navbar-expand-lg navbar navbar-with-menu navbar-fixed navbar-shadow navbar-brand-center">
    <div class="navbar-header d-xl-block d-lg-block  d-none">
        <ul class="nav navbar-nav flex-row">
            <li class="nav-item"><a class="navbar-brand" href="{% url 'main:home'%}">
                    <span class="brand-logo">
                        <img src="{% static  '/images/2-t.png'%}" class="img-fluid" alt="Brand logo" style="object-fit:contain; width:auto;  height:65px;">
                    </span>
                </a>
            </li>
        </ul>
    </div>
    <div class="navbar-wrapper">
        <div class="navbar-container content">
            <div class="navbar-collapse" id="navbar-mobile">
                <div class="mr-auto float-left bookmark-wrapper d-flex align-items-center">
                    <ul class="nav navbar-nav">
                        <li class="nav-item mobile-menu d-xl-none mr-auto"><a
                                class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i
                                    class="ficon feather icon-menu"></i></a></li>

                    </ul>
                    <ul class="nav navbar-nav bookmark-icons">
                        <li class="nav-item d-none d-lg-block">
                            <a class="nav-link" href="{% url 'main:home'%}" data-toggle="tooltip"
                                data-placement="top" title="نظام تنظيم ومتابعة نقل الطرود-التحكم">
                                فيرفاري-التحكم
                                <i class="ficon feather "></i></a></li>
                    </ul>
                </div>
                <ul class="nav navbar-nav float-right">
                                    
                    <li class="nav-item d-none d-lg-block"><a class="nav-link nav-link-expand"><i
                                class="ficon feather icon-maximize"></i></a></li>
                    <style>
                        .my-dropdown-user-link {
                            display: inline-block;
                            position: relative;
                            vertical-align: middle;
                            padding: 10px 10px;
                            text-align: left;
                        }
                    </style>

                   
                    
                    <li class="dropdown dropdown-user nav-item">
                        <a class="dropdown-toggle nav-link dropdown-user-link" href="#" data-toggle="dropdown">
                            <div class="user-nav d-sm-flex d-none">
                                <span class="user-name text-bold-600">{{ request.user}}
                                </span><span class="user-status">
                                {{ group_s }}</span></div><span><img
                                    class="" {% if user_cus.logo %} src="{{user_cus.logo.url}}" {%else%} src="{% static  '/NoImage/No-profile-image.png'%}" {% endif %}
                                    alt="{{user}}" style="object-fit:contain; width:auto;  height:45px;"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            {% if group_marketer == True   %}
                            <a class="dropdown-item" href="{% url 'dashboard:home'%}" data-toggle=""
                                data-target=""><i class="feather icon-user"></i>
                                صفحة الموظف </a>
                            {% endif %}

                            {% if group_admin == True %}
                            <a class="dropdown-item" href="{% url 'dashboard:home'%}" target="_blank"><i
                                    class="feather icon-user" target="_blank"></i>
                                 صفحة مدير النظام </a>
                            {% endif %}
                            <a class="dropdown-item"
                                href="{% url 'dashboard:page_account_settings'  %}"><i
                                    class="feather icon-user" ></i>
                                 البروفايل</a>
                           
                            <div class="dropdown-divider">
                            </div>

                            <a class="dropdown-item" href="{% url 'dashboard:home' %}"><i
                                    class="feather icon-power"></i>
                                 خروج</a>

                        </div>
                    </li>
                  
                </ul>
            </div>
        </div>
    </div>
</nav>

main/templates/main/barcode_scanner.html
<!-- barcode_scanner.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Barcode Scanner</title>
    <script src="https://unpkg.com/@zxing/library@latest"></script>
    <style>
        #interactive {
            position: relative;
            width: 100%;
        }
        #interactive video {
            width: 100%;
        }
        #barcode-result {
            margin-top: 20px;
            font-size: 1.5em;
            color: green;
        }
    </style>
</head>
<body>
    <h1>Scan Barcode</h1>
    <div id="interactive" class="viewport">
        <video id="video" width="300" height="200" style="border: 1px solid gray"></video>
    </div>
    <div id="barcode-result">Waiting for barcode...</div>
    <script>
        window.addEventListener('load', function() {
            const codeReader = new ZXing.BrowserMultiFormatReader();
            console.log('ZXing code reader initialized');

            codeReader
                .listVideoInputDevices()
                .then((videoInputDevices) => {
                    // Try to find the back camera
                    const backCamera = videoInputDevices.find(device => device.label.toLowerCase().includes('back')) || videoInputDevices[0].deviceId;

                    codeReader.decodeFromVideoDevice(backCamera.deviceId, 'video', (result, err) => {
                        if (result) {
                            console.log(result);
                            document.getElementById('barcode-result').innerText = `Barcode detected: ${result.text}`;
                            alert(`Barcode detected: ${result.text}`);
                            codeReader.reset();
                        }
                        if (err && !(err instanceof ZXing.NotFoundException)) {
                            console.error(err);
                            document.getElementById('barcode-result').innerText = `Error: ${err}`;
                        }
                    }).catch((err) => {
                        console.error(err);
                        document.getElementById('barcode-result').innerText = `Error: ${err}`;
                    });
                })
                .catch((err) => {
                    console.error(err);
                    document.getElementById('barcode-result').innerText = `Error: ${err}`;
                });
        });
    </script>
</body>
</html>

templates/base.html
{% load static  %}
{% load i18n %}


{% get_current_language as LANGUAGE_CODE %}


<!DOCTYPE html>
<html class="loading" lang="ar" data-textdirection="rtl" >
<!-- BEGIN: Head-->



{% block appheader %}

{% endblock appheader %}




<body
    class="horizontal-layout horizontal-menu  content-detached-left-sidebar ecommerce-application navbar-floating footer-static  "
    data-open="hover" data-menu="horizontal-menu" data-col="content-detached-left-sidebar" style="background-color: #f1f1f1;"><!-- #dcebef-->


    <!-- BEGIN: Header-->
    {% include 'main/navbar.html' %}
    <!-- END: Header-->


    <!-- BEGIN: Main Menu-->
    <div class="horizontal-menu-wrapper">
        <div class="header-navbar navbar-expand-sm navbar navbar-horizontal floating-nav navbar-light navbar-without-dd-arrow navbar-shadow menu-border"
            role="navigation" data-menu="menu-wrapper">
            <div class="navbar-header">
                <ul class="nav navbar-nav flex-row" id='navid'>
                    <li class="nav-item mr-auto"><a class="navbar-brand" href="{% url 'main:home'%}">
                            <div class="">
                                <img src="{% static  '/images/2-t.png'%}" class="img-fluid" alt="Brand logo">
                            </div>

                            <h2 class="brand-text mb-0">  فيرفاري -للشحن </h2>
                        </a></li>
                    <li class="nav-item nav-toggle"><a class="nav-link modern-nav-toggle pr-0" data-toggle="collapse"><i
                                class="feather icon-x d-block d-xl-none font-medium-4 primary toggle-icon"></i><i
                                class="toggle-icon feather icon-disc font-medium-4 d-none d-xl-block collapse-toggle-icon primary"
                                data-ticon="icon-disc"></i></a></li>
                </ul>
            </div>
            <!-- Horizontal menu content-->
            <div class="navbar-container main-menu-content" data-menu="menu-container">
                <!-- include ../includes/mixins-->
                <ul class="nav navbar-nav " id="main-menu-navigation" data-menu="menu-navigation">
                    <li class=" dropdown nav-item {% if '/ ' in request.path %} active {% endif %}" id="ullihomeactive" data-menu=""><a class=" nav-link "
                            href="{% url 'main:home'%}" data-toggle=""><i class="feather icon-home "></i><span
                                data-i18n="">  الرئيسية </span></a>

                    </li>
                   
                    <li class="dropdown nav-item {% if '/products' in request.path %} active {% endif %}" id="ulliservicesactive" data-menu=""><a class="nav-link"
                            href="" data-toggle=""><i
                                class="feather icon-briefcase"></i><span data-i18n="UI Elements">
                                 الشحن </span></a>
                                 <ul class="dropdown-menu">
                                    <li data-menu=""><a class="dropdown-item" href="{% url 'main:express'%}"  data-toggle="" data-i18n="Profile"><i
                                                class="feather icon-package"></i> المستندات والطرود </a>
                                    </li>
                                    <li data-menu=""><a class="dropdown-item" href="{% url 'main:forwarding'%}" data-toggle="dropdown"
                                            data-i18n="Account Settings"><i class="feather icon-bar-chart"></i>
                                            المنصات النقالة والحاويات والبضائع </a>
                                    </li>
                                   
        
                                </ul>

                    </li>
                    <li class="dropdown nav-item {% if '/companies' in request.path %} active {% endif %}" id="ullicompaniesactive" data-menu=""><a class=" nav-link"
                        href="{% url 'main:branches'%}" data-toggle=""><i class="feather icon-globe" ></i><span
                                data-i18n="Forms &amp; Tables">  الفروع </span></a>

                    </li>
                    <li class="dropdown nav-item {% if '/companies' in request.path %} active {% endif %}" id="ullicompaniesactive" data-menu=""><a class=" nav-link"
                        href="{% url 'main:faq'%}" data-toggle=""><i class="feather icon-help-circle" ></i><span
                                data-i18n="Forms &amp; Tables">  الاسئلة الاكثر تداولاً </span></a>

                    </li>
                    <li class="dropdown nav-item {% if '/scan' in request.path %} active {% endif %}" id="ullicompaniesactive" data-menu=""><a class=" nav-link"
                        href="{% url 'main:barcode_scanner'%}" data-toggle=""><i class="feather icon-help-circle" ></i><span
                                data-i18n="Forms &amp; Tables">مسح الباركود</span></a>

                    </li>
                    <li class="dropdown nav-item {% if '/scan' in request.path %} active {% endif %}" id="ullicompaniesactive" data-menu=""><a class=" nav-link"
                        href="{% url 'main:barcode_scannergemini'%}" data-toggle=""><i class="feather icon-help-circle" ></i><span
                                data-i18n="Forms &amp; Tables">مسح الباركود2</span></a>

                    </li>

                   
                </ul>
            </div>
        </div>
    </div>









    <!-- BEGIN: Content-->
    {% block appbody %}

    {% endblock appbody %}



    <div class="sidenav-overlay"></div>
    <div class="drag-target"></div>



    <!-- BEGIN: Footer-->
    <footer class="footer footer-static footer-light navbar-shadow" style="background-color: #ffffff;">

        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-7 offset-md-1 offset-lg-0">
                    <!-- About -->
                    <div class="block about ">
                        <!-- footer logo 
          <img src="images/logo1.png" height="100" alt="">
		  -->
                        <!-- description -->
                        <a href="">
                            <h1 class="alt-color"> نظام تنظيم ومتابعة نقل الطرود  </h1>
                        </a>
                        <p class="alt-color">
                           {{footer.valueText}}
                        </p>
                    </div>
                </div>
                <!-- Link list -->
                <div class="col-lg-2 offset-lg-1 col-md-3 ">
                    <div class="block">
                        <!-- <h4>الصفحات</h4>-->
                        <ul class="ul-without-bullets center">
                            <li>
                                <a href=""> 'Home' </a>
                            </li>

                            <li>
                                <a href=""> 'Products and Services' </a>
                            </li>
                            <li>
                                <a href=""> 'Companies' </a>
                            </li>

                            <li>
                                <a href="#"> 'Contact Us' </a>
                            </li>
                            <li>
                                <a href="#">'About Us' </a>
                            </li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
        <p class="clearfix blue-grey lighten-2 mb-0"><span class="float-md-left d-block d-md-inline-block mt-25"> All rights reserved </span><span
                class="float-md-right d-none d-md-block">COPYRIGHT
                &copy; <script>
                    var CurrentYear = new Date().getFullYear()
                    document.write(CurrentYear)
                </script></span>
            <button class="btn btn-primary btn-icon scroll-top" type="button"><i
                    class="feather icon-arrow-up"></i></button>
        </p>
    </footer>
    <!-- END: Footer-->





    {% block appfooter %}

    {% endblock appfooter %}


<!--

    <script>
        var a = document.querySelectorAll("#navid li a");
        for (var i = 0, length = a.length; i < length; i++) {
            console.log('nav script')
            console.log(a)
            a[i].onclick = function () {
                var b = document.querySelector("#navid li.active");
                console.log(b)
                if (b) b.classList.remove("active");
                this.parentNode.classList.add('active');
            };
        }
    </script>
    -->

   



</body>
<!-- END: Body-->

</html>

templates/basedashboard.html
{% load static  %}
{% load i18n %}


{% get_current_language as LANGUAGE_CODE %}


<!DOCTYPE html>
<html class="loading" lang="ar" data-textdirection="rtl" >
<!-- BEGIN: Head-->



{% block appheader %}

{% endblock appheader %}




<body
    class="horizontal-layout horizontal-menu  content-detached-left-sidebar ecommerce-application navbar-floating footer-static  "
    data-open="hover" data-menu="horizontal-menu" data-col="content-detached-left-sidebar" style="background-color: #f1f1f1;"><!-- #dcebef-->


    <!-- BEGIN: Header-->
    {% include 'dashboard/navbar.html' %}
    <!-- END: Header-->


    <!-- BEGIN: Main Menu-->
    <div class="horizontal-menu-wrapper">
        <div class="header-navbar navbar-expand-sm navbar navbar-horizontal floating-nav navbar-light navbar-without-dd-arrow navbar-shadow menu-border"
            role="navigation" data-menu="menu-wrapper">
            <div class="navbar-header">
                <ul class="nav navbar-nav flex-row" id='navid'>
                    <li class="nav-item mr-auto"><a class="navbar-brand" href="{% url 'main:home'%}">
                            <div class="">
                                <img src="{% static  '/images/2-t.png'%}" class="img-fluid" alt="Brand logo">
                            </div>

                            <h2 class="brand-text mb-0">فيرفاري-التحكم</h2>
                        </a></li>
                    <li class="nav-item nav-toggle"><a class="nav-link modern-nav-toggle pr-0" data-toggle="collapse"><i
                                class="feather icon-x d-block d-xl-none font-medium-4 primary toggle-icon"></i><i
                                class="toggle-icon feather icon-disc font-medium-4 d-none d-xl-block collapse-toggle-icon primary"
                                data-ticon="icon-disc"></i></a></li>
                </ul>
            </div>
            <!-- Horizontal menu content-->
            <div class="navbar-container main-menu-content" data-menu="menu-container">
                <!-- include ../includes/mixins-->
                <ul class="nav navbar-nav " id="main-menu-navigation" data-menu="menu-navigation">
                    <li class=" dropdown nav-item {% if '/ ' in request.path %} active {% endif %}" id="ullihomeactive" data-menu=""><a class=" nav-link "
                            href="{% url 'dashboard:home'%}" data-toggle=""><i class="feather icon-home "></i><span
                                data-i18n="">  الرئيسية </span></a>

                    </li>
                   
                    <li class="dropdown nav-item {% if '/products' in request.path %} active {% endif %}" id="ulliservicesactive" data-menu=""><a class="nav-link"
                            href="" data-toggle=""><i
                                class="feather icon-briefcase"></i><span data-i18n="UI Elements">
                                 حركة الطرود </span></a>
                                 <ul class="dropdown-menu">
                                    <li data-menu=""><a class="dropdown-item" href="{% url 'dashboard:sendpck'%}" data-toggle="" data-i18n="Profile"><i
                                                class="feather icon-bar-chart"></i>ارسال طرد جديد</a>
                                    </li>
                                    <li data-menu=""><a class="dropdown-item" href="{% url 'dashboard:movepck'%}" data-toggle="dropdown"
                                            data-i18n="Account Settings"><i class="feather icon-bar-chart"></i>
                                            تسجيل حركة لطرد</a>
                                    </li>
                                    <li data-menu=""><a class="dropdown-item" href="{% url 'dashboard:arrivepck'%}" data-toggle="dropdown"
                                        data-i18n="Account Settings"><i class="feather icon-bar-chart"></i>
                                        تسجيل وصول لطرد</a>
                                </li>
        
                                </ul>

                    </li>
                   
                   

                </ul>
            </div>
        </div>
    </div>









    <!-- BEGIN: Content-->
    {% block appbody %}

    {% endblock appbody %}



    <div class="sidenav-overlay"></div>
    <div class="drag-target"></div>



    <!-- BEGIN: Footer-->
    <footer class="footer footer-static footer-light navbar-shadow" style="background-color: #ffffff;">

        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-7 offset-md-1 offset-lg-0">
                    <!-- About -->
                    <div class="block about ">
                        <!-- footer logo 
          <img src="images/logo1.png" height="100" alt="">
		  -->
                        <!-- description -->
                        <a href="">
                            <h3 class="alt-color">نظام تنظيم ومتابعة نقل الطرود-التحكم</h3>
                        </a>
                        <p class="alt-color">
                           {{footer.valueText}}
                        </p>
                    </div>
                </div>
                <!-- Link list -->
                <div class="col-lg-2 offset-lg-1 col-md-3 ">
                    <div class="block">
                        <!-- <h4>الصفحات</h4>-->
                        <ul class="ul-without-bullets center">
                            <li>
                                <a href=""> 'Home' </a>
                            </li>

                            <li>
                                <a href=""> 'Products and Services' </a>
                            </li>
                            <li>
                                <a href=""> 'Companies' </a>
                            </li>

                            <li>
                                <a href="#"> 'Contact Us' </a>
                            </li>
                            <li>
                                <a href="#">'About Us' </a>
                            </li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
        <p class="clearfix blue-grey lighten-2 mb-0"><span class="float-md-left d-block d-md-inline-block mt-25"> All rights reserved </span><span
                class="float-md-right d-none d-md-block">COPYRIGHT
                &copy; <script>
                    var CurrentYear = new Date().getFullYear()
                    document.write(CurrentYear)
                </script></span>
            <button class="btn btn-primary btn-icon scroll-top" type="button"><i
                    class="feather icon-arrow-up"></i></button>
        </p>
    </footer>
    <!-- END: Footer-->





    {% block appfooter %}

    {% endblock appfooter %}

</body>
</html>